default:
	#pandoc -V documentclass=acm_proc_article-sp report.txt -o report.pdf --bibliography=biblio.bib --csl=acm-sig-proceedings-long-author-list.csl
	#pandoc -s -V documentclass=acm_proc_article-sp report.txt -o report.tex --bibliography=biblio.bib --csl=acm-sig-proceedings-long-author-list.csl
	#open report.pdf
	pdflatex report.tex
	#pandoc report.txt -o report.pdf --bibliography=biblio.bib --csl=acm-sig-proceedings-long-author-list.csl
	open report.pdf


